### ISSUE TITLE
Support no-value cookies?

### ISSUE THREAD

**Issue by domenic** [bsittler/async-cookies-api#1]
Apparently `document.cookie` supports cookies with no value via `document.cookie = "foo"`. This is distinct on the wire (i.e. in the resulting HTTP headers) from cookies with value empty string (`document.cookie = "foo="`).

Is support for this needed, so that this API encompasses the entire cookie data model, or can we be stricter?

Related: https://github.com/whatwg/html/issues/804

**Comment by bsittler** [comment]
One option (though it complicates the API slightly) would be to default to stricter https://tools.ietf.org/html/rfc6265#section-4.1 rules by default, but have a flag to permit relaxation to https://tools.ietf.org/html/rfc6265#section-5.2 rules when absolutely necessary for interoperability, e.g. ... {[' permissive ']: true} - similarly the read APIs could have an option to relax parsing ... {[' permissive ']: true}

**Comment by bsittler** [comment]
Another alternative to all this would be a radically simpler API - navigator.getCookies().then(jar => {...} ) which is merely an async read of document.cookie, and nagicator.setCookie(string).then(() => {...}) which is merely an async write of document.cookie

@cramforce what do you think? how much hand-holding, parsing assistance, etc. is actually useful?

**Comment by bsittler** [comment]
(that's more or less the original proposal by @slightlyoff  from https://github.com/slightlyoff/ServiceWorker/issues/707#issue-86384003 )

**Comment by domenic** [comment]
Forked that radically simpler API discussion to https://github.com/bsittler/async-cookies-api/issues/8

**Comment by bsittler** [comment]
See also this discussion of nameless and/or valueless cookies:

https://www.ietf.org/mail-archive/web/http-state/current/msg00320.html

The cookie RFC says valueless set-cookie attempts are ignored, but in fact browsers do not seem to ignore them.

**Comment by bsittler** [comment]
@abarth - do you have any idea whether valueless cookies are used in the real world?

**Comment by abarth** [comment]
@bsittler If they exist in the wild, they're exceedingly rare.  They certainly have cropped up at least once in the past.  If you're defining a new API for cookies, I wouldn't worry about them.  It's debatable whether folks implementing existing APIs (i.e., document.cookie and Set-Cookie) ought to worry about them.

**Comment by bsittler** [comment]
[The new explainer](explainer.md) outlines a more restrictive API which disallows both reading and writing no-value cookies. Some of the other inconsistencies mentioned here are implicitly addressed by that outline (character set: always UTF-8 for reading and writing/USVString from script perspective, max-age: not present in the proposed API for writing cookies, multiple occurrence of the same attribute: not possible in the proposed API for writing cookies) but the rest still need to be addressed.

**Comment by bsittler** [comment]
Fixed explainer link

**Comment by domenic** [comment]
Please stop spamming my inbox with notifications that you edited a post :(. We can all just see the new post...

**Comment by bsittler** [comment]
Will do, didn't realize!

**Comment by bsittler** [comment]
Further reading of the cookie compatibility results from https://inikulin.github.io/cookie-compat/ make it fairly obvious that there is de-facto standard behavior for Set-Cookie with no '=' across all browsers tested except Safari. Specifically, it is treated identically to the same Set-Cookie prefixed with '=', and updates the cookie with the empty-string name. I will go ahead and follow the majority behavior here in the polyfill and assume the spec will probably be changed to match that.
