### ISSUE TITLE
What is the meaning of 'path' in accessors?

### ISSUE THREAD

**Issue by jakearchibald** [bsittler/async-cookies-api#10]
`has`/`get`/`getAll` take a path but don't do anything with it at the moment.

**Comment by jakearchibald** [comment]
https://github.com/bsittler/async-cookies-api/issues/4 is somewhat related.

When I was sketching a similar design (https://github.com/slightlyoff/ServiceWorker/issues/707#issuecomment-187732390) I couldn't settle on "match" or "get". "get" doesn't map well.

WIth the singular get/match, "name" is required, it doesn't make sense otherwise. With getAll/matchAll the name is optional. It feels like the APIs should reflect that. Eg:

```js
navigator.cookies.match(name, { path });
navigator.cookies.matchAll({ name, path });
```

In the singular match, I'm not sure what the default path should be, maybe it should be required too.

Additionally I can't decide if "path" should be treating the path as a key, or a scope. Eg:

```js
navigator.cookies.matchAll({
  path: someRequest.url
});
```

Should the above return me all cookies with their path set to `someRequest.url`, or should it return me all the JS-visible cookies that would be sent along with a request to `someRequest.url`?

**Comment by jakearchibald** [comment]
I think trying to fit this into a map-like shape is confusing things.

Maybe it should be simpler?

`getAll` - takes no arguments, returns all the cookies for the domain. This means you can get multiple entries with the same name but different paths. Filtering is left to the developer.

No `get` method to avoid confusion around defaults and how "path" works.

`forURL(url)` - returns the JS-visible cookies that would be sent along with a request to `url`. `url` could default to the client url, making `forURL()` return the same set of cookies as `document.cookie`. "name" would be unique in the returned cookies, so it could be a map.

**Comment by jakearchibald** [comment]
> returns all the cookies for the domain

Hmm, I guess it should only be "cookies for this origin and parent origins". Exposing cookies targeted to other subdomains would be bad.

**Comment by bsittler** [comment]
Exposing paths and/or domains is new information not currently visible on
the web. Cookie:/reading document.cookie does not tell you the path or
domain, only the name and value.

Allowing the path to be specified seems OK, but I think requiring it is
odd, at least in document contexts. I think it should default to the path
of the current page.

**Comment by bsittler** [comment]
(Also, specifying a read path just means you get back all cookies in-scope
at that path, including those set at parent paths.)

**Comment by jakearchibald** [comment]
> Exposing paths and/or domains is new information not currently visible on the web. Cookie:/reading document.cookie does not tell you the path or domain, only the name and value.

Right, but should we carry on that tradition? I can work out the path of cookies by loading an iframe and brute forcing the url & seeing how `document.cookie` changes.

> Allowing the path to be specified seems OK, but I think requiring it is odd, at least in document contexts. I think it should default to the path of the current page.

If you can specify the path, you make the above hack even easier.

> (Also, specifying a read path just means you get back all cookies in-scope
at that path, including those set at parent paths.)

I don't disagree with that behaviour, but it makes this very un-map-like. The meaning of "path" in get/set becomes quite different.

**Comment by bsittler** [comment]
My only intent when including a path argument was to allow a ServiceWorker to see script-visible cookies which would be in-scope for a given Fetch interception.

**Comment by jakearchibald** [comment]
Yep, it's a good use-case

**Comment by jakearchibald** [comment]
> "name" would be unique in the returned cookies, so it could be a map.

No it wouldn't. TIL multiple cookies of the same name are sent in this case.

**Comment by domenic** [comment]
> Right, but should we carry on that tradition?

I think we have to, otherwise this API is useless. The original point of this API was to allow people to manage cross-site logins in their service workers.

**Comment by jakearchibald** [comment]
@domenic I was referring to exposing the path of a cookie. Discussion split off into https://github.com/bsittler/async-cookies-api/issues/11

**Comment by bsittler** [comment]
I've attempted to address this issue in [the explainer](explainer.md) (where path is called 'url' instead). Please take a look there and let me know what you think.

In particular, I think the IFRAME-based brute-forcing is preventable by a server rigorously sending X-FRAME-OPTIONS: DENY provided the user isn't tricked into allowing a pop-up. What do you think?

**Comment by bsittler** [comment]
Fixed explainer link

**Comment by bsittler** [comment]
Polyfill for document contexts and explainer are synced now on this issue. Re-open if you think the path restrictions are problematic (and explain why, please!)
