### ISSUE TITLE
synchronous errors should not be thrown by promise-returning methods

### ISSUE THREAD

**Issue by domenic** [bsittler/async-cookies-api#2]
An easy way to fix this is to move the `return new Promise(...` to the top and then just throw errors as before. They will be automatically caught and converted into promise rejections.

**Comment by bsittler** [comment]
Just for my education: is this the consensus (or standard?) answer for https://github.com/domenic/promises-unwrapping/issues/24

**Comment by domenic** [comment]
Yep. See also https://www.w3.org/2001/tag/doc/promises-guide#always-return-promises

**Comment by bsittler** [comment]
I believe this is done now, largely thanks to the move to `async`.
