### ISSUE TITLE
What exactly does .get() with no args do? Is it useful?

### ISSUE THREAD

**Issue by domenic** [bsittler/async-cookies-api#4]
Most "multimap" style APIs do not allow .get() with no args. (That is, they treat it as `.get("undefined")`.) This seems to get the first cookie with any key? Is that useful? Seems like a weird part of API design.

**Comment by bsittler** [comment]
No, this gives back a map of cookie names to cookie values, containing only the first value for any multi-valued cookies (exactly as if each cookie name was passed to .get(name) in turn); this is useful for apps that either don't care about multi-valued cookies, or always want the first value.

**Comment by domenic** [comment]
OK. I think that should be a separate API, instead of overloading .get(). Same with .getAll(). "get" means "get from the multimap by key".

Maybe .asObject() and .asObject({ multivalues: true }) or something.

**Comment by bsittler** [comment]
This wrinkly is not present in the newer API outlined in [the explainer](explainer.md). I will update the polyfill to match that newer API, as amended by any further discussion between now and when I finish updating it.

**Comment by bsittler** [comment]
Fixed explainer link
