### ISSUE TITLE
What about Origin cookies?

### ISSUE THREAD

**Issue by bsittler** [bsittler/async-cookies-api#6]
@mikewest is working on https://tools.ietf.org/html/draft-west-origin-cookies-01 which looks pretty awesome, but it also appears to create a new, separate cookie jar for origin cookies. Should there be a separate navigator.originCookies to prevent confusion? Will documents also have a document.originCookie to allow reading this jar?

**Comment by domenic** [comment]
Hmm. My impression was that `document.cookie` would also work with origin cookies. I wonder what @mikewest's intent was.

It would be nice if the "evil" (cross-origin) cookies got a longer name than the "good" (origin-restricted) ones. So `navigator.cookies` vs. `navigator.originCookies` is a bit sad. One way of doing this is making people pass `{ allowCrossOrigin: true }` to all the methods of this API.

But that is maybe not a good idea if they are supposed to be truly separate cookie jars. If they are separate cookie jars then two different instances of this repo's `CookieJar` makes sense. It's just kind of a shame how the names shake out.

**Comment by bsittler** [comment]
My assumption was that document.cookie should reflect the non-HttpOnly subset of what the Cookie request header would contain for a fresh Fetch to the page's URL to avoid breaking the web. Since Origin cookies don't appear in Cookie, but rather in a separate Origin-Cookie header, I think there needs to be a separate JavaScript accessor too, at least for reading them. Otherwise JavaScript fails to benefit at all from the Origin flag since it can't tell by reading document.cookie whether a particular cookie name/value pair there is a regular cookie (which may come from some other [possibly less secure] context) or an origin cookie.

**Comment by mikewest** [comment]
Origin cookies are on the backburner for the moment; there's very little interest from other vendors, and I think 80% of the benefit is captured via the `__HOST-` prefix (https://tools.ietf.org/html/draft-ietf-httpbis-cookie-prefixes-00#section-3.2).

I don't think we need to worry about them in this API. If we do end up needing to worry about them in the future, we'll work it out then. :)

**Comment by bsittler** [comment]
Thanks! I went ahead and included some references to the prefix proposal in [the new explainer](explainer.md) - please take a look and let me know what you think.

**Comment by bsittler** [comment]
Fixed explainer link

**Comment by bsittler** [comment]
Given the prefix proposal I'm going to close this; if there is ever revived interest in Origin cookies this can be revisited
