### ISSUE TITLE
Larger philosophical point: should this be able to do everything document.cookie can do, or just a sane subset?

### ISSUE THREAD

**Issue by domenic** [bsittler/async-cookies-api#7]
Right now this API is very flexible. Issues like #3 and #1 play into a larger theme, which is what use cases this API is for.

Personally I think it might make sense to be more restrictive and only add features to this API that serve concrete use cases, instead of saying "anything you can do with document.cookie, you can do with this API." We definitely want to minimize the number of people that drop back to sync document.cookie, or people who can't accomplish their goals inside workers because their favorite cookie-related feature is missing. But I really am not sure that modern websites are purposefully using things like no-value cookies or extended attributes or cookie names/values that don't match the RFC's grammar.

So personally I'd prefer to start as restrictive as possible in those regards, and wait for users to surface use cases for more lenient behavior.

**Comment by bsittler** [comment]
I decided I agree with this proposal, and the initial API outlined in [the explainer](explainer.md) does not include a `document.cookie`-compatible escape hatch. On the other hand it does permit most of the things websites actually use document.cookie for. We can always add the escape hatch later (in one form or another), but if on the other hand it proves unneccessary it would be hard to take back once given to web content.

**Comment by bsittler** [comment]
Fixed explainer link
