### ISSUE TITLE
String-based API *plus* nice cookie API

### ISSUE THREAD

**Issue by domenic** [bsittler/async-cookies-api#8]
In https://github.com/bsittler/async-cookies-api/issues/1#issuecomment-192504735 @bsittler mentioned just a simple API for async setting/getting of the cookie string, like `document.cookie` except it can be used in workers and is async.

We chatted about this a bit and then he had a brilliant idea: "why not both?"

That is: we expand this current proposal with promise-returning `getAsString()` and `setAsString(s)` objects, which do exactly what `document.cookie` does, just async and works-in-workers. UAs could implement this small subset almost immediately! In the meantime, we could work on making a nicer cookie API, like this repo already has, as additional methods (`get`/`getAll`/`set`/etc.).

This also neatly resolves #7. We can make the nice API a bit more restrictive, with the escape hatch of {get,set}AsString to take care of the crazy esoteric cases like no-value cookies for anyone who really needs them.

**Comment by domenic** [comment]
Better bikeshed color: `readAsString()` and `writeAsString()` to avoid confusion with `get` = "get from the multimap by key" and similarly for `set`.

**Comment by bsittler** [comment]
readAllAsString().then(jar => { ...}) perhaps?

**Comment by domenic** [comment]
What is jar in that example? A string or a `CookieJar`?

**Comment by bsittler** [comment]
A string, exactly as from a (synchronous) evaluation of document.cookie in rvalue context.

**Comment by bsittler** [comment]
Specifically, a string like "NAME1=VALUE1; NAME2=VALUE2; NAME1=VALUE3; ... etc." exactly as would be seen in the HTTP "Cookie" header, but with HttpOnly pairs filtered out.

**Comment by domenic** [comment]
OK cool. Yeah that name seems reasonable. I just got confused by your variable name.

**Comment by inexorabletash** [comment]
What are the use cases for this? Is there anything script can (or should) do with this API other than wrap it with a custom (i.e. fragile/buggy...) parser/serializer?

It would make for easier interop with existing code (i.e. custom cookie APIs with parsers/serializers)  and be easy for UAs to implement, but IMHO those - on their own - don't seem to justify the inclusion.

I could imagine a use case for getting/setting the whole shebang at once, and/or having a pre-serialized form (e.g. to store/send elsewhere?) but I haven't heard of those. Are those real or just my fevered imagination?

**Comment by bsittler** [comment]
I think it's mainly useful as a "minimum viable API" for access to cookies from workers (and other async contexts where blocking on any sort of cookie mutex/disk access is unacceptable.) It also directly exposes the *only* cookie abstraction currently visible to scripts and web servers, so library and framework support for this should be a lot less difficult than adapting to a completely new higher-level API with its own abstractions.

Finally, a higher-level API can be implemented in terms of this one, so it may be possible to reach implementer consensus early on the "minimum" API with broad availability, then iterate rapidly on polyfills of the higher-level API separately without blocking those worker-based web applications which are in dire need of cookie access today.

**Comment by bsittler** [comment]
After further though I think the Set-Cookie/Cookie-like API presented by document.cookie is bad enough (especially in terms of defaults) that I do not want to perpetuate it. So instead the new API proposed in [the explainer](explainer.md) only offers a higher-level abstraction. I would like to see how far we get with that, and whether an escape-hatch is actually needed, before committing to maintaining one indefinitely as part of the new API. What do you think?

**Comment by annevk** [comment]
It sounds reasonable, but we really need to be sure that all applications can migrate to the new API.

**Comment by bsittler** [comment]
I mostly agree. I think the vast majority of applications need to work with
the new API without any major change to how they use cookies.

However, I'm sure there are unusual edge cases where an application only
works in a subset of modern browsers, or uses and relies on differences
cookie behavior in different browsers, and I'm not convinced those need to
keep working without modifications.

**Comment by annevk** [comment]
Yeah, on reflection it's worth starting out small (as I said elsewhere in the past I noticed), but make sure we can grow to the full feature set which is always possible by adopting the string-based `document.cookie` elsewhere.

**Comment by bsittler** [comment]
Fixed explainer link

**Comment by bsittler** [comment]
String-based API (class AsyncCookieJar_) is there now and used internally in CookieStore but is not exported. Re-open if you think it should be exported (and explain why, please!)
